### ISSUE TITLE
Let's include authentication alerts in logincounts 

### ISSUE THREAD

**Issue by mpurzynski** [mozilla/MozDef#1015]
https://github.com/mozilla/MozDef/blob/7f84b7aee64533fbd21526a806dc8a82ed70c751/rest/plugins/logincounts.py#L75

The logincounts REST plugin looks for events of category authentication, how about we make it also take 'failed logins' alerts into account as well?

**Comment by jeffbryner** [comment]
It does look for failed logins? It starts by gathering a list of all failed logins, then looks for success logins and creates a data stream counting each category.

**Comment by Phrozyn** [comment]
We've removed the visualization for logincounts for now, there will be a kibana dashboard for this, and future plans are to surface those visualizations to the UI.
