### ISSUE TITLE
Feature Request: Configurable host IPs

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#1033]
So, I'm using the docker containers as a deployment in my infrastructure and generally I really like it. However one thing that is annoying is clicking a link (say Kibana) and being sent to `localhost:9090`. I've make a hot edit in `meteor/imports/settings.js` to hard code my ip in use, but it would be really nice if I could give mozdef an ip at deploy time. ex `make run my_ip=1.2.3.4` or `make run config=my_overrides.txt/json` or something along those line. Being able to change out the elastic search service would also be nice.

I get that I might be using the docker containers in a way that they are not designed for so if this is out of scope just let me know and I'll rework what I have based on the alternate install method.

**Comment by darakian** [comment]
I'm not sure I understand. In the first link I see that Meteor is doing a self check to see if it should be using default values or not which I guess are set in the Dockerfile linked second. I'm not sure where PORT 3000 comes from though and I don't see it in link #1. As for the cloudy env file; I can't find that anywhere.

**Comment by jeffbryner** [comment]
Oh, sorry. So Meteor is programmed to look at the environment first and use that if it's set. 

You can set the environment via Docker in a couple different ways: 
1) When you build a container you can set ENV lines in the Dockerfile directly
2) When you use docker compose, you can specify a .env file to use for the 'service' presented by the container. 

So for your case, I'd say create a .env file and modify the docker-compose. The .env file is just: 
VARIABLE=value

So if you wanted to set the kibana location you'd include a file, say meteor.env with 
OPTIONS_METEOR_KIBANAURL=https://somewhere

**Comment by darakian** [comment]
An env file certainly seems the maintainable approach. Looking at the use of 
```
env_file:
      - cloudy_mozdef.env
```
It seems that each docker container is being passed the same env file for overrides. Given your description of an env file I'm wondering if this is because there are reused variables or if there are somehow sections to the `cloudy_mozdef.env` file.

My mental model for the moment is that I have my build system insert lines
```
env_file:
      - clear_mozdef.env
```
for each service (those I care about) and to configure my env as desired. One immediate question is; how do I know what I can override? Is the `cloudy_mozdef.env` file available anywhere for reference?

**Comment by jeffbryner** [comment]
Good question, @gene1wood do we have that file in a repo anywhere or a reference of what's in it?

**Comment by gene1wood** [comment]
Indeed, it's generated by the [CloudFormation template](https://github.com/mozilla/MozDef/blob/c6866d5f5a9c8af8bf77c439db116d5309d59e2c/cloudy_mozdef/cloudformation/mozdef-instance.yml#L115-L141)

**Comment by darakian** [comment]
So, as I read this file the elastic search server and kibana server are external via this configuration. 
`${ESURL}` defining elastic search and 
`${KibanaURL}` defining kibana
OpenID seems to be used for accounts  and a few options are set.

The only major thing I'm not seeing is if I can override a tls cert file.
Thank you much for the link!

**Comment by gene1wood** [comment]
> the elastic search server and kibana server are external

Correct, in our MozDef for AWS deployment we use AWS ElasticSearch which is external

>  OpenID seems to be used for accounts and a few options are set.

Yes, accessing Kibana, hosted by AWS with the ElasticSearch service, is done through our OIDC Proxy (which also fronts the MozDef UI)

> The only major thing I'm not seeing is if I can override a tls cert file.

Tell me more, which cert do you want to override and what do you want to change it to?

**Comment by darakian** [comment]
Long term it might be desirable to change this to a cert associated with my company domain. The relevant containers are probably meteor and log input.

**Comment by darakian** [comment]
User defined env available via
https://github.com/mozilla/MozDef/pull/1072
