### ISSUE TITLE
Doc Request: Using log entry data in alert summary example. 

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#1034]
Is there a preferred method for using data from the result a query in the alert summary? For instance, I have a `PhraseMatch('summary', 'interesting string prefix')` which works well, but I would like to pull out some of the summary string and have that available on the MozDef alerts dash board. I'm sure this is possible to hack together, but is there a method already in place? If so could someone point me at an example?

**Comment by jeffbryner** [comment]
Great question. Assuming this is an aggregated alert you get event data burped up to the alert in three ways: 
a count
a reminder of the aggregation value
a subset of the events that matched

Here's an example of the ssh bruteforcing alert using that to include some counts in the summary field: 
https://github.com/mozilla/MozDef/blob/master/alerts/bruteforce_ssh.py#L44

You could do similar to pull out, say, the first summary from an event that tripped the alert like so: 
summary = ('Alert on: {0} '.format(aggreg['events'][0]['summary']))

i.e. you are using the aggreg['events'] list and just selecting the first one to grab the 'summary' field and copying it into the alert summary.

**Comment by darakian** [comment]
What are the events in this context though? Say for the bruteforce_ssh alert.

**Comment by jeffbryner** [comment]
They would be anything that matched the query parameters set in the alert. So in this case: 
https://github.com/mozilla/MozDef/blob/master/alerts/bruteforce_ssh.py#L18

Any events matching that ('failed' in the summary, from the details.program:'sshd', with any of 'login', 'invalid', 'ldap_count_entries', 'publickey', 'keyboard' also in the summary) within the timeperiod of the alert (run every minute, looking back 10 minutes). 

So you can pull out individual fields, aggregate counts (the mostCommon routine for example) of any field in that record set.

**Comment by darakian** [comment]
So these are the full log events? Ex. say I have a tag on all my logs 'foo', the following would return true?
`bool('foo' in aggreg['events'][0][tags])`

**Comment by pwnbus** [comment]
@darakian FYI it would be `'foo' in aggreg['events'][0]['_source']['tags']`

**Comment by darakian** [comment]
I see. `_source` because all the ground truth log info is contained within `_source`?
