### ISSUE TITLE
Note field in Notes tab has white text on a white background

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1062]
When filling in the `Note` field of the `Notes` tab in MozDef, the text is white text on a white background making it invisible. If you select the text in the textbox you can see it but otherwise not.

Please change the CSS so this is the same text color as other textboxes and can be seen

**Comment by gene1wood** [comment]
Here's the CSS line causing the problem

https://github.com/mozilla/MozDef/blob/c6866d5f5a9c8af8bf77c439db116d5309d59e2c/meteor/public/css/mozdef.css#L197

**Comment by jeffbryner** [comment]
It's actually a typo here: https://github.com/mozilla/MozDef/blob/master/meteor/client/incidentEdit.html#L415
