### ISSUE TITLE
Unable to send test logs via https

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#1073]
I'm not sure if I should be able to, but I can't curl logs at a basic docker instance of mozdef. Is there any setup required to get basic https support for the log input docker container? Curl output below.
```
jon~/r/g/s/s/s/m/mozdef-broker:mozdef-broker❯❯❯ curl -v --header "Content-Type: application/json" --data '{"summary": "just an https test"}' https://my-mozdef.com:8080/events
*   Trying 1.2.3.4...
* TCP_NODELAY set
* Connected to my-mozdef.com (1.2.3.4) port 8080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
* stopped the pause stream!
* Closing connection 0
curl: (35) error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number
```

Edit:
If it matters I'm on macOS Mojave with`LibreSSL 2.6.5` as my ssl provider

**Comment by Phrozyn** [comment]
docker logs should work to get logs. 
https://docs.docker.com/engine/reference/commandline/logs/

Are you trying to programmatically obtain the logs?
There's another docker document on logging drivers here which would facilitate delivery of logs from the container to the logging driver you choose.
https://docs.docker.com/config/containers/logging/configure/

**Comment by Phrozyn** [comment]
Wrong version number makes me think there's a tls version mismatch, though it shows you are using TLSv1.2 in the connection. To use SSL with loginput you really should be going through the nginx proxy, rather than using ssl to connect directly to the container. The nginx proxy will facilitate passing the logs through to loginput.

**Comment by darakian** [comment]
Ah I see. Are there docs somewhere on setting up the nginx proxy or on which port I should be sending my logs to for it to go through the proxy?

**Comment by pwnbus** [comment]
If you're using the docker environment, the reason you're getting a version mismatch, is because the loginput service on port 8080 is not TLS (as we don't wrap any services within the docker environment with TLS currently).

**Comment by darakian** [comment]
That would explain it. Thanks!

**Comment by pwnbus** [comment]
You can try and use something like https://github.com/jwilder/nginx-proxy which does support TLS to throw in front of the mozdef nginx proxy container for now, but I also wonder if we should just create a self signed cert for dev and put in the mozdef nginx container, so out of the gate, we expose ports on both plaintext and TLS connections. I created https://github.com/mozilla/MozDef/issues/1142 to do that.

**Comment by darakian** [comment]
For our purposes we need a load balancer anyway, so we're using that to handle TLS.
