### ISSUE TITLE
Docker ENV override ESURL issues

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#1077]
I'm trying to use the docker containers as a deployment for my mozdef and would like to break out the ES service. At the moment I'm using the recently merged `run-env-mozdef` to provide a variable `ESURL: https://example.bar`. Due to a bug in the `run-env-mozdef` codepath I'm hardcoding the ENV_FILE variable to make this work. 

In actuality the url is a VPC endpoint provided by the AWS ES service of the form `https://vpc-foo.country-region-num.es.amazonaws.com`

The problem is that I can't tell if/how it's working. The about page in a mozdef instance is blank which makes me feel that the connection is not being made, but I'm unsure of to proceed in debugging. My questions are a) am I working along the correct path and b) is there any advice on how to proceed with debugging an external ES cluster?

Edit:
One more question Am I correct in thinking that the `mozdef_mq_worker` container is the container which ships logs to the ES service?

Edit 2:
Seems that the `OPTIONS_ESSERVERS` is the real variable that breaks things which is (in my case) inherited from `ESURL`

Edit 3:
Curling the vpc endpoint returns what I think is a standard ES son reply with the `"tagline" : "You Know, for Search"` which makes me think that the network is in order. The mq worker reliably crashes with the following 
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 1084, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/mozdef/envs/mozdef/mozdef_util/mozdef_util/bulk_queue.py", line 15, in timer_over
    self.flush()
  File "/opt/mozdef/envs/mozdef/mozdef_util/mozdef_util/bulk_queue.py", line 50, in flush
    self.es_client.save_documents(self.list)
  File "/opt/mozdef/envs/mozdef/mozdef_util/mozdef_util/elasticsearch_client.py", line 113, in save_documents
    bulk(self.es_connection, documents)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/opt/mozdef/envs/python/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 99, in _process_bulk_chunk
    raise e
ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7ffb5d1fd610>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7ffb5d1fd610>: Failed to establish a new connection: [Errno -2] Name or service not known)
```

**Comment by jeffbryner** [comment]
Yup the mq workers are responsible for pulling json from rabbit, running through the plugins and depositing in ES. 

If you can curl the ES endpoint and you get the version/tagline json response then the ES instance is working. So then it's a matter of ensuring the mq workers know where to point and can reach the endpoint.
Sounds like you can curl the ES endpoint. If it were me, next up I'd see if you can also curl from the mqworker container? i.e. get a shell (docker exec -it <container id or name> bash ) ? If so, is the environment variable right in the container?

**Comment by darakian** [comment]
I can indeed curl from the mq worker container. Looks like the env isn't being set properly with $(ESURL) being taken literally.
```
[mozdef@384ef1bea0e0 mq]$ env
HOSTNAME=384ef1bea0e0
TERM=xterm
ES={"servers": [${ESURL}]}
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/opt/mozdef/envs/python/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/opt/mozdef/envs/mozdef/mq
TZ=UTC
SHLVL=1
HOME=/opt/mozdef
affinity:container==3d976843239f7f1a732d89666035ef3ad8aee24d7a2788b342d000ea34c414f2
OPTIONS_ESSERVERS=${ESURL}
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/usr/bin/env
```

**Comment by darakian** [comment]
The more I look at this the more I think it might be a better idea to have the docker-compose file be the user supplied information and make available a template with static env file. Everything I'm reading leads me to believe that `gnu make` cannot set environmental variables for processes outside of itself. Compound this with the lack of input options for `docker-compose` and the "single config input from mozdef user" is difficult to achieve.

@jeffbryner Any thoughts?
