### ISSUE TITLE
NOTE: Docker pull mozdef_base login issue/build issues

### ISSUE THREAD

**Issue by exenin** [mozilla/MozDef#1117]
Using docker-compose up --build
the build fails and complains about not being able to pull from
mozdef_base:latest 

This is due to compose naming the image 
compose_*

solved by simply retagging 
docker tag compose_base mozdef_base:latest

**Comment by pwnbus** [comment]
Instead of running raw docker-compose commands, we did our best to abstract that away into make file targets, so you can simply run `make build` and `make run` instead.

**Comment by Phrozyn** [comment]
https://mozdef.readthedocs.io/en/latest/installation.html#build-and-run-mozdef <-- we could probably do a better job of explaining each of the options available in the [Makefile](https://github.com/mozilla/MozDef/blob/master/Makefile) in our documentation. 

As pwnbus pointed out, there's:

- make build
- make run
- make stop
- make rebuild
- make clean

And a few other special use-cases.
