### ISSUE TITLE
Disable globe visualization in default deployment, enabling it only when MozDef is configured to show data on the globe

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1119]
Currently the globe visualization (located at the `/globe` path in MozDef) doesn't display any data in MozDef out of the box. The logic to search and label an attacker is currently pretty specific to Mozilla which results in anyone else who deploys MozDef having a globe visualization with no data.

Let's make the globe's presence conditional on whatever it is we do to put data into it and by default, show no globe.

Thanks to @darakian for calling this out.

**Comment by jeffbryner** [comment]
This is part of the feature flagging and you can turn off all the visualizations (globe/attackers are the same data) or just the globe, just the attackers, etc. Currently the features are all on by default, but you can turn them off as you wish. https://github.com/mozilla/MozDef/issues/936

**Comment by gene1wood** [comment]
@jeffbryner What do you think about defaulting the visualizations that don't work out of the box to disabled in feature flagging? If that's a good idea should I open a new issue on that or is this issue good for it?

**Comment by jeffbryner** [comment]
It's not that they don't work, they may just not have any data? i.e. attackers are the combination of events->alerts->attackers. If you run the sample data demo events you'll get some created in just a couple minutes. 

But out of the box the whole system doesn't have data, so if we use that criteria then we disable alerts, kibana, etc?

**Comment by gene1wood** [comment]
@jeffbryner Ah sorry I'd misunderstood. @pwnbus had said "the logic to search and label an attacker is currently pretty specific to mozilla I believe, so we’d have to figure out a way to have folks customize that per environment"

If indeed the globe *does* work out of the box (as soon as data comes in), I'll work with the MozDef team to figure out why @darkian isn't getting any data vis in the globe in his deployment.

**Comment by jeffbryner** [comment]
If it helps, it creates attackers based on hitcount and ipv4 address. i.e. if someone from the same IP block creates X alerts it becomes an attacker: 
https://github.com/mozilla/MozDef/blob/master/cron/collectAttackers.py#L154

**Comment by darakian** [comment]
For what it's worth all of our logs are currently coming from private IP address ranges. I'm not sure if we can map them to public or not, but it's not a big deal.

**Comment by jeffbryner** [comment]
ah, that'd would explain it. There's specific logic here https://github.com/mozilla/MozDef/blob/master/cron/collectAttackers.py#L171 to not create attackers out of 'friendly' ip address ranges.

**Comment by darakian** [comment]
I think most of our logs will be routed over private IP space for the foreseeable future. A nice thing to have in the future would be to be able to define which field the IP address is in for a given type of log. ex. we have some application logging which has the same /16 (/24 maybe) subnet used for the log source, but we could embed the IP of given user session in those logs. This would allow for application level visuals which would be nice (for me :))

**Comment by jeffbryner** [comment]
Ah, good point. You could accomplish that currently by using a custom plugin to do something similar to this: https://github.com/mozilla/MozDef/blob/master/mq/plugins/ipFixup.py#L129 if the actual 'source ip' comes in via a header or similar method.

**Comment by darakian** [comment]
That's good to know about, but I don't want to alter the logs and change the source of truth (which is what I think that function does). I suppose I could alter the logging logic to send two copies; one with and one without the `'message['details']['cluster_client_ip']` field.
