### ISSUE TITLE
docs/source/_static/theme_overrides.css matches .gitignore. Which do we want?

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1217]
.gitignore asserts that all files in `docs/source/_static` should be ignored however the file `docs/source/_static/theme_overrides.css` is committed.

Do we want to remove `theme_overrides.css` or modify the `.gitignore` file?

**Comment by gene1wood** [comment]
[`docs/source/_static/theme_overrides.css`](docs/source/_static/theme_overrides.css) is used by [`docs/source/conf.py`](docs/source/conf.py)

Anyone know why
* `docs/source/_static` is set to be ignored in `.gitignore`?
* why this one file is present in that directory, violating .gitignore?
* if `.gitignore` should be fixed or if `theme_overrides.css` shouldn't be in the repo?

**Comment by Patil2099** [comment]
I think the file should be removed. 
https://www.git-tower.com/learn/git/faq/ignore-tracked-files-in-git
