### ISSUE TITLE
Change CodeBuild to use different OS

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1250]
Ubuntu 14.04 goes EOL in CodeBuild May 15 2019. Please update and test building on a new OS

https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html

This will require manual changes to the CodeBuild settings as well as updates to [`buildspec.yml`](https://github.com/mozilla/MozDef/blob/master/cloudy_mozdef/buildspec.yml)

**Comment by andrewkrug** [comment]
We use the latest Docker environment available presently.  When AWS bumps the version we'll get it into the pipeline.
