### ISSUE TITLE
Why is the placeholder text for a new incident summary what it is?

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1307]
The placeholder text in a new incident summary field found at

https://mozdef.example.com/incident/new

 is

```
'Category: 'activity' on 'affected target''
```

What does this mean? Is this a template of what type of information should be entered in the summary? Are `activity` and `affected target` meant to be variables such that a summary should look like `Category: Unauthorized login on db backend`?

Or is `Category` also a variable?

And if this is a template, we can probably remove those confusing leading and trailing quotes.

**Comment by jeffbryner** [comment]
Looks like it's meant to be a prompt so the summary can be useful on it's own, long after the context of the incident is lost in time. 

i.e. DOS: Web scraping on MDN is much more useful than "Website slow"
