### ISSUE TITLE
[Docker env] Alerts not being displayed - Cron silently failing in container

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#1315]
Hey All,

I've got a box on the current master. It's generating alerts fine, but the mozdef dash board doesn't display the alerts. I've verified that the alerts are created by looking at the ES cluster and the alerts index exists and contains the expected results. Any ideas on where I should be looking for the alert display part of the equation?

This is in the docker environment and nothing pops out at me after looking at the logs for each container.

**Comment by pwnbus** [comment]
Hey,
     The alerts get propogated from Elasticsearch to Mongodb by a cron script (specifically https://github.com/mozilla/MozDef/blob/master/cron/syncAlertsToMongo.py) which then show up in the mozdef dashboard.

This script "should" be running as part of the mozdef_cron container. Do you get any errors if you do:
 `docker exec mozdef_cron_1 bash`
  `su mozdef`
  `/opt/mozdef/envs/mozdef/cron/syncAlertsToMongo.sh`

**Comment by darakian** [comment]
No errors but that populated the alerts

**Comment by darakian** [comment]
Running the python script `/opt/mozdef/envs/mozdef/cron/syncAlertsToMongo.py` directly and doing some printf style debugging I'm coming to the conclusion that the the cron schedule is to blame.

**Comment by darakian** [comment]
Update on this. The issue seems to stem from systemd being unable to run and crond relies on systemd in this OS.
```
[mozdef@e9bb5d12deae /]$ systemctl
Failed to get D-Bus connection: Operation not permitted
[mozdef@e9bb5d12deae /]$ exit
exit
[root@e9bb5d12deae /]# systemctl
Failed to get D-Bus connection: Operation not permitted
```
Docker seems to block access to systemd by default.
https://serverfault.com/questions/824975/failed-to-get-d-bus-connection-operation-not-permitted


I'm looking into a fix for this. So far adding privileged mode, the cgroup volume and the cap SYS_ADMIN to cron in the `docker-compose.yml` file have not allowed systemd to run.

**Comment by pwnbus** [comment]
The logs you're seeing:
```
2019-06-04T22:26:10.143137785Z bash: connect: Connection refused
2019-06-04T22:26:10.143157915Z bash: /dev/tcp/elasticsearch/9200: Connection refused
```
are from the docker containers command value, which is basically "sleeping until elasticsearch is avaiable", and stems directly from this line -> https://github.com/mozilla/MozDef/blob/master/docker/compose/docker-compose.yml#L125

These errors can be ignored.

**Comment by pwnbus** [comment]
We shouldn't need systemd to work here, as the cron scripts are in fact, executing, just every minute, so I'm unsure what you're trying to accomplish here?

**Comment by darakian** [comment]
I figured as much after digging around. At this point my thought process is that a new deploy had an updated version of docker which blocks systemd and thus cron from within containers. This seems to be a prevalent issue with a systemd replacement script even
https://github.com/gdraheim/docker-systemctl-replacement

**Comment by darakian** [comment]
Ok. Scratch the systemd thought. I've got cron running in the docker container on a centos 7 machine. The issue seems to be on centos6/amazon linux 1 only. I think the path of least resistance is to update my base OS. Sorry for the noise and thanks for letting me think out loud.
