### ISSUE TITLE
Communication issue with demo instance and sample data

### ISSUE THREAD

**Issue by iJebus** [mozilla/MozDef#1347]
Hey, I was trying to play around with a demo instance following the [docs ](https://mozdef.readthedocs.io/en/latest/demo.html) and ran into some trouble.

I cloned the repo and then ran `docker-compose -f docker/compose/docker-compose.yml -f docker/compose/dev-sampledata.yml -p mozdef up`. That created a demo instance that I can could login to and browse around but sampledata was spamming connection refused.

To get past this I tweaked some files to let the sampledata container reach the nginx container:

dev-sampledata.yml:
```
     command: bash -c 'while ! timeout 1 bash -c "echo > /dev/tcp/elasticsearch/9200 && echo > /dev/tcp/nginx/8080";do sleep 1;done && /opt/mozdef/envs/mozdef/examples/demo/sampleevent
s.sh'
     links:
       - nginx
```

sampleData2MozDef.py:
```
options.url = getConfig('url', 'http://nginx:8080/events/', options.configfile)
```

I doubt this is the intended flow though. Maybe the docs could be made clearer?

**Comment by Phrozyn** [comment]
Thank you for the report.
There's a makefile for the docker containers that you can just by just entering into the mozdef top level directory and issuing make build  and make run, or even just make run will build and run it for you, and it will include all that's needed.
