### ISSUE TITLE
MozDef virtualenv version conflicts with mozdef-util tox version

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1370]
MozDef's requirements.txt installs both
* `mozdef-util=3.0.1`
* `virtualenv==1.11.4`

mozdef-util 3.0.1's setup.py installs 
* `tox>=3.5.2`

Modern `tox` requires `virtualenv>=14.0.0` producing this error on installation

`ERROR: tox 3.13.2 has requirement virtualenv>=14.0.0, but you'll have virtualenv 1.11.4 which is incompatible.`

1. Does `mozdef_util` actually need tox or could we remove it since it's used for testing (and rely on it in `requirements_dev.txt` in `mozdef_util`)?
2. If not can we update our `virtualenv` requirement in MozDef?

**Comment by pwnbus** [comment]
I think when we created mozdef_util package, we used a boilerplate template, so we can probably remove tox as a requirement?

Also, I suspect we don't even need to have virtualenv as part of our dependencies, and it was only added when we did something like `pip freeze` a few years ago to match the source code requirements to what we had running in prod at the time.
