### ISSUE TITLE
Docker fails to Connect to D Bus and install Elasticserach

### ISSUE THREAD

**Issue by goffr2** [mozilla/MozDef#1472]
When using the docker compose method of building mozdef I keep getting:
Failed to connect to DBus Operation not premitted
Then it won't install elasticsearch. ideas? Fixes?

**Comment by pwnbus** [comment]
Hmm, I use docker-compose on a pretty daily basis and haven't had any problems installing/building recently. Can you paste the full output that you're seeing?

**Comment by goffr2** [comment]
is there someplace all the output from make build is stored? It happens in the make build process.

**Comment by pwnbus** [comment]
If you're running `make build`, then the text that I'm asking for is what will get printed to the screen during that process.

**Comment by goffr2** [comment]
I'll rerun make build on a new host and post the output give me a couple of hours

**Comment by pwnbus** [comment]
Sounds good, just an FYI (I don't know if you're running into that problem or not), but `make build` takes ~15 minutes to finish, and now that we've enabled threaded builds in docker-compose, the output on the screen might be a bit misleading as behind the scenes, we might be building a few containers at once.

**Comment by pwnbus** [comment]
If you want to simply run the docker environment, we do publish our images to dockerhub, so you can run `make run BUILD_MODE=pull` which might be a bit faster.

**Comment by goffr2** [comment]
https://pastebin.com/vSPaGf6B
I was able to capture most of the make build process. When I run make build and make run everything works except for localhost:9200 which I think is due to elasticsearch not being installed. I installed it manually on my other vm and it works. idk if it with work with kibana though which is why I want to use docker

**Comment by goffr2** [comment]
bump

**Comment by pwnbus** [comment]
Looking at the output, the ES docker container did infact build correctly:
```
Created elasticsearch keystore in /etc/elasticsearch
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
Cleaning up list of fastest mirrors
Removing intermediate container 1794e3c64ce2
 ---> 574e4245be07
Step 6/11 : USER elasticsearch
 ---> Running in 47bd32a8dd01
Removing intermediate container 47bd32a8dd01
 ---> 794a5a7782e0
Step 7/11 : COPY docker/compose/elasticsearch/files/elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
 ---> 2d927f5faf0e
Building elasticsearch ... done
 ---> 1ff74b7d5611
Step 9/11 : VOLUME /var/lib/elasticsearch
 ---> Running in 4a6ef6467de5
Removing intermediate container 4a6ef6467de5
 ---> ad4add4e25f1
Step 10/11 : WORKDIR /usr/share/elasticsearch
 ---> Running in 5eb5809cac96
Removing intermediate container 5eb5809cac96
 ---> 8cee0a4927e7
Step 11/11 : EXPOSE 9200
 ---> Running in 31dbeab9a9b1
Removing intermediate container 31dbeab9a9b1
 ---> 5a1d1fe5b7d1
```

By default, Elasticsearch won't be exposed to the local docker host, so I'm not sure how you're verifying that it does not work.

After you run `make run`, you can do `docker logs -f mozdef_elasticsearch_1` to see if the elasticsearch docker container starts up successfully.

**Comment by pwnbus** [comment]
You can also exec into one of the mozdef containers which does have network access to the elasticsearch container, for example:
`docker exec -it mozdef_cron_1 bash` and then `curl http://elasticsearch:9200`

**Comment by goffr2** [comment]
Your correct. My apologizes. My issue is I'm trying to send metrics via metric beat. Following the kibana guide I setup metricbeat and get the following errors when trying to send data to elastic:

Rickys-MacBook-Pro:metricbeat-6.8.0-darwin-x86_64 ricky$ ./metricbeat setup
Exiting: Couldn't connect to any of the configured Elasticsearch hosts. Errors: [Error connection to Elasticsearch http://192.168.0.171:9200: Get http://192.168.0.171:9200: dial tcp 192.168.0.171:9200: connect: connection refused]
Rickys-MacBook-Pro:metricbeat-6.8.0-darwin-x86_64 ricky$

**Comment by goffr2** [comment]
I'm following the kibana tutorial and I dont know what I'm doing wrong. I assumed elasticsearch wasn't installed

**Comment by goffr2** [comment]
Here is my metricbeat.yml
https://pastebin.com/UizpgKca

**Comment by goffr2** [comment]
bump

**Comment by pwnbus** [comment]
We don't run metricbeat, so unfortunately we aren't able to help. I'm closing the issue since the original question (ES not starting up) is I believe "solved".
