### ISSUE TITLE
Standardize "raw" field name and format

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1607]
Currently various plugins and cron fetchers use different field names when capturing a copy of the raw message that's being parsed. They also use different methods to serialize the data. Some use `str()`, others `json.dumps()` or the built in `repr` method.

# `rawdetails`
[broFixup.py](https://github.com/mozilla/MozDef/blob/6ede727ee2c34ccf61ef196c7645bca74f4952a4/mq/plugins/broFixup.py#L83)
[suricataFixup.py](https://github.com/mozilla/MozDef/blob/6ede727ee2c34ccf61ef196c7645bca74f4952a4/mq/plugins/suricataFixup.py#L50)

# `raw_value`
[cloudtrail.py](https://github.com/mozilla/MozDef/blob/6ede727ee2c34ccf61ef196c7645bca74f4952a4/mq/plugins/cloudtrail.py#L78)

# `raw`
[auth02mozdef.py](https://github.com/mozilla/MozDef/blob/6ede727ee2c34ccf61ef196c7645bca74f4952a4/cron/auth02mozdef.py#L357)

Would it make sense to standardize on one of these names so these raw messages all use the same field and store data in the same format?

Would a good format for that to be stored in (since this is stored in elastic search) be JSON? If so we should remember to set these field types from `t` to `?` so ES knows they contain JSON

**Comment by Phrozyn** [comment]
I absolutely agree we should standardize, but the disparity comes from lack of formalization of a standard and different developers writing the different modules. @pwnbus I'd love to hear your thoughts!

**Comment by gene1wood** [comment]
@pwnbus What do you think about this? What's a good next step on this (e.g. open a Jira ticket? assign this to someone?)

**Comment by Phrozyn** [comment]
This is something we will tackle with our upcoming normalization efforts.
I'll add this to my requirements and plan. 
:) Thank you, Gene, for reminding me of this with your update!

**Comment by gene1wood** [comment]
If/when #1653 is merged then there are only two raw field names, `raw_value` and `rawdetails`
