### ISSUE TITLE
WebUI: kibana dashboards refreshes all the time

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/MozDef#170]
Not much data, but simply changing from screen to screen forces a kibana dashboard refresh REST call. Cache the data in a session var? Update on a timer? Once every x page changes? Would save some data transfer/screen lag.

**Comment by 526avijitgupta** [comment]
@jeffbryner There already seems to be a [publish](https://github.com/jeffbryner/MozDef/blob/master/meteor/app/lib/collections.js#L258) and [subscribe](https://github.com/jeffbryner/MozDef/blob/master/meteor/app/lib/collections.js#L335) in place for `kibanadashboards` .  Does the REST call really need to be for each screen change ?

**Comment by jeffbryner** [comment]
No, it doesn't need to happen for each screen change. Just needs to check for new dashboards once every x minutes/seconds?
