### ISSUE TITLE
Does this diagram match the architecture you have in mind?

### ISSUE THREAD

**Issue by joenoll** [mozilla/MozDef#1717]
Hi,

my team and I are currently working on an automated generation of architecture diagrams for CloudFormation and serverless projects. Your project is particularly interesting as it represents a good real-world use case. 

The tool we are working on generated the [following diagram](https://dashboard.codeshield.io/public/result/82efbf95-df0c-4fd6-b5d4-c7c8c890e0a5?utm_source=github.com&utm_medium=share-graphs&utm_campaign=teamA) for your repo. I am happy to get your feedback about it. It would be very helpful for our product development. 

Does the diagram match the architecture you have in mind? 

Cheers, 
Joe

**Comment by pwnbus** [comment]
Please do not use github issues to market your product and company.
