### ISSUE TITLE
AWS Changing GuardDuty finding type September 1, 2021

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#1723]
Notification on upcoming changes to Amazon GuardDuty finding type :

* The finding called [`UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration`](https://github.com/mozilla/MozDef/blob/bca65c274d363d56c417caada64be05e8585cd68/mq/plugins/guardduty_mapping.yml#L1481-L1498) will be replaced with the name “UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration.OutsideAWS”
* The renamed finding type "UnauthorizedAccess:IAMUser/InstanceCredentialExfiltration.OutsideAWS" will improve the accuracy of the existing finding type by learning the remote networks that instance credentials associated with your AWS account are used from. Once GuardDuty learns the expected behavior, it will only generate an alert if the remote network the EC2 instance credentials are used from is unusual for your account.

MozDef needs to be updated to use this new finding type name

**Comment by claudijd** [comment]
Internal Tracker: https://mozilla-hub.atlassian.net/browse/SEC-2749
