### ISSUE TITLE
Can't log on the Mozdef

### ISSUE THREAD

**Issue by hankyzz** [mozilla/MozDef#202]
```
I can't log on the Mozdef ! Although I also use the Mozllia account and a yahoo account, but still no response, bothering me for a long time, can  you give me advice about it?
I have modified the  “ forbidClientAccountCreation:true,” with false，but  does not work！
```

   And when I visit 8080 and  8081 ，it tells me  “Sorry, the requested URL 'http://ServerName:8080/' caused an error:    Not found: '/'  ”

**Comment by poyw911** [comment]
Hey jeff, this is Di. 
I was just googling about the problems i sent you through the emails, and found this guy was having similar issues. I have my settings.js information matches /etc/nginx/nginx.conf and all the exports. But I am still having the same problem: "sorry, the reuqested URL 'http://localhost:8081/' casued an error: Not Found: '/' " for rest and loginput uwsgi. 
Let me know if you already had a solution in mind. 
Thanks!

**Comment by yashmehrotra** [comment]
@poyw911 What is the output `http://localhost:8081/status`. Because the `404` you are getting maybe bottle's 404 response.
