### ISSUE TITLE
WebUI: Bug in investigations/incident tabs related to tab activating/hiding

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/MozDef#225]
Fast (double or single) clicking the tabs in the investigations or incident screens can result in a previous tab still being displayed.

**Comment by 526avijitgupta** [comment]
@jeffbryner I am facing difficulty in reproducing this, does it still seem to occur ?

**Comment by jeffbryner** [comment]
Yeah, it does.. just happened to me the other day. If you click around in the tabs really fast it seems to trigger

**Comment by Phrozyn** [comment]
I think I just reproduced this. It does change tab, but I can see the old tab's fields at the bottom of the new tab window, I got this to happen with 3 different tabs, ending with the last window having 2 other tab's fields stacked at the bottom.

**Comment by Phrozyn** [comment]
![screen shot 2017-07-20 at 9 44 48 pm](https://user-images.githubusercontent.com/4267984/28447148-b49e7448-6d94-11e7-83e5-87057607c72b.png)
