### ISSUE TITLE
Deprecate pyes in favor of elasticsearch-dsl

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/MozDef#319]
In order to migrate to elastic search 2.x, we need to remove pyes and migrate to elasticsearch-dsl: 
http://elasticsearch-dsl.readthedocs.org/en/latest/
http://elasticsearch-py.readthedocs.org/en/latest/helpers.html#bulk-helpers

**Comment by jeffbryner** [comment]
Some patterns: 


from elasticsearch import Elasticsearch
from elasticsearch import helpers
from elasticsearch_dsl import Search, Q
from elasticsearch_dsl.connections import connections
from datetime import datetime

es=connections.create_connection(hosts=['esServerName.Somewhere.com'])
#create event to send
def genEvent():
    anevent={
          "category": "jabtest",
          "processid": "0",
          "receivedtimestamp": datetime.now(),
          "severity": "7",
          "utctimestamp": datetime.utcnow(),
          "timestamp": datetime.utcnow()
        }
    return anevent

actions=[]
for j in range(0, 10):
    a=genEvent()
    action = {
        "_index": "events",
        "_type": "event",
        "_source": genEvent()
        }
    actions.append(action)
print(actions)

if len(actions) > 0:
    print(helpers.bulk(es, actions))

**Comment by jeffbryner** [comment]
Parallel bulk: 

````python
#parallel bulk: 
from elasticsearch.helpers import parallel_bulk
actions=[]
for j in range(0, 10):
    a=genEvent()
    action = {
        "_index": "events",
        "_type": "event",
        "_source": genEvent()
        }

    actions.append(action)
for ok,result in parallel_bulk(es,actions,thread_count=4, chunk_size=500):
    print(ok,result)
````

**Comment by pwnbus** [comment]
This has been fixed in https://github.com/mozilla/MozDef/pull/399
