### ISSUE TITLE
Break out zData.gui.min.js

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/MozDef#324]
While incorporating the awesomeness that is the VR visualizations I noticed that the file zData.gui.min.js seems to be a concatenation of a couple different js libraries: 

https://stemkoski.github.io/Three.js/Particle-Engine.html seems to be the main inspiration which in turn relies on:
https://github.com/stemkoski/stemkoski.github.com/blob/master/Three.js/js/ParticleEngine.js
https://github.com/stemkoski/stemkoski.github.com/blob/73ad62f1792d1ca7c7658c39ee0ebe4c9220bba1/Three.js/js/ParticleEngineExamples.js

The core data.gui.min.js file doesn't appear to be used in the VR display. 

We should break out this file into the various source files for easier tracking of the component .js files for future updates, etc?

@526avijitgupta @yashmehrotra @DarkPrince304 can you confirm my analysis?

**Comment by 526avijitgupta** [comment]
@jeffbryner Good catch.

It would make sense to break the code into different files. We'd just have to care about loading the files in the required order. And maybe that's the initial reason that we had actually concatenated different files together. 

@darkprince304 Need your confirmation on this.

**Comment by DarkPrince304** [comment]
Agreed. I'll fix this and send in a PR soon.

**Comment by jeffbryner** [comment]
Punting to the end of march release to publish the feb release.

**Comment by jeffbryner** [comment]
closing this as this was removed when updating to modern meteor.
