### ISSUE TITLE
Using docker container

### ISSUE THREAD

**Issue by technion** [mozilla/MozDef#325]
Hi,

I'm testing out this product with a docker container as per http://mozdef.readthedocs.org/en/latest/installation.html#docker, but I seem to be running into a few issues.

The first is making the container stay online. At the moment, following:

sudo make run
(once inside as root)
/etc/init.d/supervisor start

But if you then type "exit" and close the session, the container exits and shuts down. How do you keep this running?

~~While the container is still running, I have tested that I can access port 9000 (Kibana) and 9200 (Elastichsearch) as per the guide, but 3000 doesn't seem to be responding.~~ EDIT: Well it turns out the fix here is being more patient. I gave it fifteen or so minutes, apparently the first start just needs more. The other issues remain.

Also, as a minor bug report, something about the build process creates a directory named "\[" in the container.

Any assistance with any of these issues would be appreciated.

**Comment by jeffbryner** [comment]
Sorry for the late reply. The docker container is only meant as a trial, so start a screen session first and you'll get persistence.

Yeah, it's a lot to run under docker so patience is key for the UI components to come online.

**Comment by technion** [comment]
Thanks for this clarification. I'll close this issue because you've answered my question, however, you may want to review documentation.

Docker is listed first in the installation guide, with no such warnings. The "full" installation is listed as "Alpha phase" and comes with a warning about not being tested.

**Comment by yashmehrotra** [comment]
@technion You can try the full Manual Installation, it's tested now, and should work. Those docs were a bit old so I have updated them with #326
