### ISSUE TITLE
Manual installation documentation missing a step

### ISSUE THREAD

**Issue by Phrozyn** [mozilla/MozDef#328]
In the http://mozdef.readthedocs.org/en/latest/installation.html#mozdef-manual-installation-process
The user is instructed to install mongodb, and then meteor. However, the step to start mongodb is missing (while the step to start meteor is present).

All that's needed is the following after installation:
/etc/init.d/mongod start

**Comment by yashmehrotra** [comment]
When you have installed it, you can go to `MozDef/meteor/` and then run mongodb by `$ meteor mongo`. BTW, when you start `MeteorJS`, the `mongodb` automatically starts with it. So all you have to do is:

```
$ cd <path_to_MozDef>/meteor/
$ meteor
```

**Comment by Phrozyn** [comment]
hi yashmehrotra, 

You are absolutely correct. I made a mistake on installation of mongo which is why it didn't start. 
I just caught it after testing out what you were saying.

Thanks! This will be closed.
