### ISSUE TITLE
Feature Request: Add logic to the blocking feature

### ISSUE THREAD

**Issue by Phrozyn** [mozilla/MozDef#354]
If the blocking feature only blocked the attacking IP first, and included logic to determine if a new attacker is from the same subnet as an IP that is already blocked, then it could change the /32 block to a /28, /27, /24 etc depending on how far away that subsequent attacking IP is from the original.

**Comment by VitorFalcao** [comment]
@Phrozyn Is this enhancement still needed? If so, I would like to fix this issue! I am just starting with this project, so could you give me some pointers? Thank you

**Comment by jeffbryner** [comment]
Duplicate or re-statement of #1027

**Comment by Phrozyn** [comment]
This feature has been re-factored, closing
