### ISSUE TITLE
esworker.sqs.py shouldn't dump event contents into the `details` field

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#375]
The current `esworker.sqs.py` takes incoming events passed via SQS and [dumps the contents](https://github.com/mozilla/MozDef/blob/a09e83c5cc0ca5e6bba107a66a32719145d4f013/mq/esworker.sqs.py#L304) into the `details` field of the record. This was done to accommodate how fluentd formats it's events that it submits to MozDef via SQS.

The downside to this is that clients that submit a properly formatted event data via SQS end up with the `details` field being nested inside another `details` field.

I think what we'd like to do is 
1. Get fluentd to start passing a `customendpoint` field set to `True`. This will cause the worker to [send the event to the plugins](https://github.com/mozilla/MozDef/blob/a09e83c5cc0ca5e6bba107a66a32719145d4f013/mq/esworker.sqs.py#L361-L365).
2. Create a MozDef plugin which catches these fluentd events and transforms them into the MozDef event format but putting the payload of the event in the `details` field
3. Test and confirm that fluentd events are now being transformed by this new plugin
4. Remove the `esworker.sqs.py` logic which dumps the event payload into the `details` field

Here's the current result of a fluentd event passing through `esworker.sqs.py`

```
{
  "_index": "events-20160815",
  "_type": "event",
  "_id": "PuTvRwbKSc6mwuYwrGtxVA",
  "_score": null,
  "_source": {
    "category": "syslog",
    "processid": "1977",
    "receivedtimestamp": "2016-08-15T23:48:14.235175+00:00",
    "severity": "INFO",
    "utctimestamp": "2016-08-15T23:47:55+00:00",
    "tags": [
      "nubis_events_prod"
    ],
    "timestamp": "2016-08-15T23:47:55+00:00",
    "hostname": "ip-10-164-12-101",
    "mozdefhostname": "mozdef2.private.scl3.mozilla.com",
    "summary": "INFO (transaction.py:150): Flushing 1 transaction during flush #8974260",
    "processname": "dd.forwarder",
    "source": "syslog",
    "details": {
      "destinationipaddress": "10.164.12.101",
      "ident": "dd.forwarder",
      "__tag": "ec2.forward.system.syslog",
      "region": "us-west-2",
      "pid": "1977",
      "instance_id": "i-cfb7b209",
      "instance_type": "m3.medium",
      "host": "ip-10-164-12-101",
      "program": "dd.forwarder",
      "message": "INFO (transaction.py:150): Flushing 1 transaction during flush #8974260",
      "az": "us-west-2a",
      "destinationipv4address": "10.164.12.101"
    }
  },
  "sort": [
    1471304875000
  ]
}
```

and here's an event created by [mozdef_client](https://github.com/mozilla/mozdef_client) passing through `esworker.sqs.py`

```
{
  "_index": "events-20160814",
  "_type": "event",
  "_id": "esnU8IqLQ5qAJFN7b4Zt-w",
  "_score": null,
  "_source": {
    "receivedtimestamp": "2016-08-14T13:00:13.058825+00:00",
    "tags": [
      "infosec_mozdef_events"
    ],
    "mozdefhostname": "mozdef1.private.scl3.mozilla.com",
    "utctimestamp": "2016-08-14T13:00:13.058995+00:00",
    "details": {
      "category": "event",
      "processid": 23063,
      "severity": "INFO",
      "tags": [
        "tls",
        "certificatetransparency"
      ],
      "timestamp": "2016-08-14T13:00:12.870527+00:00",
      "hostname": "ip-172-31-18-248.us-west-2.compute.internal",
      "summary": "New certificate detected in Certificate Transparency logs",
      "processname": "/home/centos/send_to_mozdef.py",
      "details": {
        "certparseable": "yes",
        "subjectdn": "C=US, ST=California, L=Mountain View, O=Mozilla Foundation, CN=static-san.mozilla.org",
        "dnsnames": [
          "static-san.mozilla.org",
          "thehub.mozilla.com"
        ],
        "entryindex": "26335940",
        "issuerdn": "C=US, O=DigiCert Inc, CN=DigiCert SHA2 Secure Server CA",
        "certtype": "cert",
        "fingerprint": "88232c30ec2a5dfbccb24bdf051e0a29abd336bea0258538b1ae49681847dfbc",
        "serial": "575e26ba3dceefaaa8d10f3aecdc202",
        "notbeforeunixtime": "1391644800",
        "pubkeyhash": "946099f6c4a738acc50695360eda49b8c0f0e5b3ef8c8ce3f027fca18dbe2ef3",
        "loguri": "https://ct.googleapis.com/pilot",
        "notafterunixtime": "1479816000"
      }
    }
  },
  "sort": [
    1471179613058
  ]
}
```

**Comment by jeffbryner** [comment]
"Get fluentd to start passing a customendpoint field set to True."

The 'customendpoint' marker is a feature from the http injestion and related esworker that pulls from rabbitmq. It serves simply as a prompt to send the event through plugins first before attempting to normalize the event (make field names the same, etc). 

We can probably start with the assumption that the SQS worker should just send all events through plugins and avoid this step. 

reference: 
https://github.com/mozilla/MozDef/blob/master/mq/esworker.sqs.py#L361

**Comment by gene1wood** [comment]
With the current message format as interpreted by the mozdef sqs worker, here are ways to search for your events

* `details.tags:foo`
* `details.hostname:ip-172-31-14-43.us-west-2.compute.internal`

And here's what the resulting event in MozDef looks like with the details within details.

```
{
  "_index": "events-20161005",
  "_type": "event",
  "_id": "ECBd7QjIT-KRTfpF0X-3fQ",
  "_score": null,
  "_source": {
    "receivedtimestamp": "2016-10-05T21:41:26.887228+00:00",
    "tags": [
      "infosec_mozdef_events"
    ],
    "mozdefhostname": "mozdef1.private.scl3.mozilla.com",
    "utctimestamp": "2016-10-05T21:41:26.908187+00:00",
    "details": {
      "category": "event",
      "processid": 11724,
      "severity": "INFO",
      "tags": [
        "foo"
      ],
      "timestamp": "2016-10-05T21:41:26.626639+00:00",
      "hostname": "ip-172-31-14-43.us-west-2.compute.internal",
      "summary": "This is my summary",
      "processname": "/path/to/my_script.py",
      "details": {
        "bar": "baz"
      }
    }
  },
  "sort": [
    1475703686908
  ]
}
```
