### ISSUE TITLE
Problem-MozDef docker

### ISSUE THREAD

**Issue by Lfengjie** [mozilla/MozDef#377]
Hello everyone:
          I follow the offcial  instuction that building a image named mozdef in ubuntu14.04, But I found some web can not access. Even the web about meteor.
         So I try to run the instuction to start service : cd ~/MozDef/mq ./esworker.py, but it shows that there is an error that No such file or directory '/home/mozdef/envs/mozdef/mq/GeoLiteCity.dat', 
        I found the right path is '/home/mozdef/envs/mozdef/bot/GeoLiteCity.dat', 
        So I want to know wheather some files are not updated in the docker. 

FengJie

**Comment by jeffbryner** [comment]
Hey, 

Thanks for taking it for a spin. You can either reconfigure it to use that location or cp the file into the mq directory. 

Jeff.

**Comment by Phrozyn** [comment]
Hello FengJie!
Let us know if there are any other questions we can help with!

**Comment by Phrozyn** [comment]
@Lfengjie 
We found the issue in the code and have pushed patch #378 to resolve this issue
Thank you for bringing this to our attention!

Some major revisions will be forthcoming in the coming months, stay tuned!

**Comment by Lfengjie** [comment]
Hey,
Thank you for your reply, I will try what you said. I decide to download v1.20 MozDef. I think it is stable.
