### ISSUE TITLE
Problem:  docker

### ISSUE THREAD

**Issue by Lfengjie** [mozilla/MozDef#380]
Hello Everyone:
     I installed MozDef with an automated build generation using docker, But When I done it, I found the webUI about meteor can't be reached after I run the instruction "/etc/init.d/supervisor start".  But sometime it is OK.
   so, can anyone help me.
   I use the v1.20 MozDef.

FengJie

**Comment by Phrozyn** [comment]
Hello FengJie, 

I'm currently testing the docker version of MozDef and will  update you as soon as I have concluded my investigation.
I have been able to duplicate the issue you mentioned.
Can you tell me what the specs are for the docker system you are running it on?

**Comment by Lfengjie** [comment]
I'm sorry I didn't see your reply!

I found the problem. It seem that MozDef will connect the network when I start it. So sometimes It can not be reached. The network I used blocking some website.

**Comment by Phrozyn** [comment]
Hello! 

Thank you for the update, I'll consider this issue closed then.
Thank you!
