### ISSUE TITLE
problem-pcap

### ISSUE THREAD

**Issue by Lfengjie** [mozilla/MozDef#385]
Hello:
        I want to ask that can MozDef handle pcap file? I found it can only handle events and logs through read the tutorial.

FengJie

**Comment by jeffbryner** [comment]
Nothing stopping one from writing a pcap parser if you just want some sample data, but you might be better off with https://github.com/aol/moloch which is written specifically to handle pcaps.

**Comment by Lfengjie** [comment]
Thank you for you reply!
