### ISSUE TITLE
Default config filename for cloudtrail2mozdef is cloudtrail2mozdef.py.conf

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#386]
`cloudtrail2mozdef.py` has an [incorrect default config file name](https://github.com/mozilla/MozDef/commit/f84e9726a703147295ea07c2ac56378ad353c945#diff-fecbc7110e9bc2c6d0e5ef5e09ccd35eR356) of `cloudtrail2mozdef.py.conf` instead of `cloudtrail2mozdef.conf`. Do it [like this instead](https://github.com/mozilla/MozDef/blob/a09e83c5cc0ca5e6bba107a66a32719145d4f013/cron/setupIndexTemplates.py#L43-L46)

**Comment by pwnbus** [comment]
Closing issue since this cron script has been converted to a worker.
