### ISSUE TITLE
WebUI: Display timezone in date/time fields

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#396]
Currently when using the MozDef meteor interface and filling out date/time fields, no timezone is indicated. My understanding is that internally the date/time is recorded in the time zone that the web user's browser is setup in. It would be great to either display this timezone so the user knows or worst case a tooltip indicating that the timezone is the local timezone of the user.

**Comment by shikhar-scs** [comment]
Is this issue still up ? (if yes) Is anyone working on it?

**Comment by Phrozyn** [comment]
This was taken care of in PR #576
