### ISSUE TITLE
Provide CI support for Python 2.7.11 - 2.7.13

### ISSUE THREAD

**Issue by claudijd** [mozilla/MozDef#406]
I'm not using the template here because the ask is pretty basic to upgrade to the 2.7.13 release of python.

This probably buys you a couple things...

- Fixes any sec bugs fixed between 2.7.11 and 2.7.13
- Get's you thinking of Python version as a moving target (compiling as part of the build, multiple python versions supported, etc.)
- Pays down tech debt of running out of date software (less obstacles between here and 3.x)

**Comment by jeffbryner** [comment]
I don't think we specify python versions (just 2.x) anywhere in the code, so should really be mostly a deployment issue for any virtual environments, etc.

**Comment by claudijd** [comment]
I do wonder if we should though, as Python revs which undoubtably changed behavior, we should have that pinned for our unit-tests or it could pass in our unit-tests on Python X and fail on Python Y.

**Comment by pwnbus** [comment]
I've pinned the unit tests down to what we are running in prod (which is 2.7.11), but that was for consistency purposes.

It would only affect our deployment process.

**Comment by claudijd** [comment]
I'm going send a PR to add .12 and .13 to travis.  This will let us know that they all work, regardless of deployment choice.

**Comment by claudijd** [comment]
I'm going to resolve this, as deployment details like what Python you want to use in Mozilla Prod aren't really relevant in the source repo.  We can now say it works on .11 - .13 and we're validating that against our unit-tests.
