### ISSUE TITLE
Remove free-form "Contributor:" text from individual code refs

### ISSUE THREAD

**Issue by claudijd** [mozilla/MozDef#407]
Just a suggestion, I feel like this is more of a Perl/pre-SCM era convention to tag modules or contributions in the code itself.  Recommend removing those in favor of having the SCM tell the story for us.

**Comment by claudijd** [comment]
example: https://github.com/mozilla/MozDef/blob/master/alerts/confluence_shell.py#L9

**Comment by Phrozyn** [comment]
I would agree with you, but this won't get set with any priority, removing them doesn't add any value aside from a few bytes in decreased filesize.
Personally, I find it interesting to see how many people have touched/modified a particular script when I open it to do the same.
At this point I don't think it serves really any other purpose than to give credit. I'll let others weigh in.

**Comment by claudijd** [comment]
@Phrozyn Seeing who touched a file in git is most conventially done with a `git blame` action in modern SCMs, which will tell you who modified each and every line and in what change set.  As to your priority comment, this is probably ~10min worth of work and IMO just good code hygiene, I'd be willing to send the PR if the effort/prioritization against other priorities was a hurdle here.

```
grep -R Contributors ./ | wc -l
241
```

**Comment by Phrozyn** [comment]
Thanks for the offer, I'll bring it up in our mozdef weekly meeting and see how the team feels, and I'll update you.

**Comment by pwnbus** [comment]
IMO, I think this text should be nuked for a couple reasons:

1. This info can get outdated, real quick and can be a pain to keep accurate. Do we have to on January 1st of every year, have to modify each and every file to update the year? 

2. Every file we edit, we need to make sure our name is in the contributors list? More developer work, for what benefit?

3. This doesn't provide any additional info that git history can't provide, while git history provides even more info that this

4. If let's say DeveloperA writes a block of code in a file, so DeveloperA appends his/her name to the file. DeveloperB comes around, and removes that block of code as part of a feature request or improvements. Does DeveloperB then remove DeveloperA from the contributors list in the file? If yes, then that means DeveloperB must identify who wrote each line of code in each file modified and make sure the contributors list at the top is accurate (which git history would be used). If DeveloperB doesn't remove DeveloperA from the list, this doesn't accurately reflect the current state of the file. DeveloperA no longer has any code in the file, so should their name remain in the file?

**Comment by yashmehrotra** [comment]
@claudijd @pwnbus @Phrozyn 
I made a PR (#578) regarding this issue.
Kindly check it out.

**Comment by pwnbus** [comment]
Also implemented https://github.com/mozilla/MozDef/pull/586 to clean up remaining lists in html/js files.
