### ISSUE TITLE
rotateIndexes.py needs some rework

### ISSUE THREAD

**Issue by Phrozyn** [mozilla/MozDef#508]
#### ISSUE TYPE
 - Bug Report

#### COMPONENT NAME
/opt/mozdef/envs/mozdef/cron/rotateIndexes.py

#### CONFIGURATION
N/A

#### OS / ENVIRONMENT
CentOS7

#### DESCRIPTION
We should consider splitting out the backup code from the actual rotation and alias update code.
We should also consider using http://elasticsearch-py.readthedocs.io/en/master/api.html?highlight=alias#elasticsearch.client.IndicesClient.rollover
Rather than deleting and then creating the alias which can sometimes cause an index with the name "events" to be created within the time frame between the delete and create calls are made.

**Comment by pwnbus** [comment]
Implemented in https://github.com/mozilla/MozDef/pull/513  Closing issue since that PR has since been merged.
