### ISSUE TITLE
Demo Instance Is Down

### ISSUE THREAD

**Issue by Miserlou** [mozilla/MozDef#534]
#### ISSUE TYPE

 - Documentation Report

The documentation [here](http://mozdef.readthedocs.io/en/latest/demo.html) links to a demo instance: http://demo.mozdef.com:3000/

However, this server is down. Please either put the server back up, or remove this link from the documentation! (Preferably the first!)

Thanks!
R

**Comment by jeffbryner** [comment]
Thanks, yeah this has been long overdue while we refactored the backend code and all the docker container(s), removing persona logins, etc. 

We should probably remove it until it's up and functional again.
