### ISSUE TITLE
Add IP to "unknown country" warning

### ISSUE THREAD

**Issue by edmorley** [mozilla/MozDef#536]
#### ISSUE TYPE
 - Feature Idea

#### COMPONENT NAME
[alerts/plugins/sso_dashboard.py](https://github.com/mozilla/MozDef/blob/d89c0eb6d098cabd8869c3b94ecf52b5d7fe2fd8/alerts/plugins/sso_dashboard.py)

#### CONFIGURATION
Mozilla's instance

#### OS / ENVIRONMENT
Mozilla's instance

#### DESCRIPTION
I filed an issue against the SSO dashboard repo (mozilla-iam/sso-dashboard#192) but was told the data came from MozDef, so re-filing here.

Upon visiting https://sso.mozilla.com/dashboard recently, I saw a "Did you recently login from Unknown, Norway?" warning. Now I very much doubt this is a real problem (and is likely just a geolocation inaccuracy), but to confirm either way I really need to know the IP address.

As such, please can the warning be modified to show the IP?

**Comment by tristanweir** [comment]
We actually just planned dealing with "Unknown" cities this for our upcoming sprint, although the UX might be slightly different than surfacing the IP.

**Comment by edmorley** [comment]
Hi! To clarify - in this case whilst the city was unknown, the country was also wrong, so fixing the city wouldn't help on it's own (unless intended fix is something different).

**Comment by pwnbus** [comment]
@edmorley I decided to include the IP address in every message, at the end. We also filter out the city now, if it is unknown.

This means for your example, the modified summary would be 'Did you recently login from Norway (1.2.3.4)?' We will also be adding the date from which it happened to the beginning of the message, which should further help in identifying the legitimacy. 

Thanks for the recommendation!

**Comment by pwnbus** [comment]
This has been pushed to production, so you should start to see the IP show up in the summary, as well as the city excluded if it is 'Unknown'. We haven't quite wrapped up the "showing the date in the summary" part yet, but hopefully that can get resolved soon.

**Comment by edmorley** [comment]
Amazing! Thank you :-)
