### ISSUE TITLE
docker alerts error

### ISSUE THREAD

**Issue by 219liangyi** [mozilla/MozDef#716]
![image](https://user-images.githubusercontent.com/19781251/41221853-f5ccd1f4-6d97-11e8-9a2f-5d5296fd4a98.png)

**Comment by jeffbryner** [comment]
Can you say some more about which docker setup you are using? We have the single instance docker (everything on one container) and the multi-instance (docker-compose).

**Comment by jeffbryner** [comment]
Can you say some more about which docker setup you are using? We have the single instance docker (everything on one container) and the multi-instance (docker-compose).

**Comment by pwnbus** [comment]
Closing issue since this is no longer an issue in master.
