### ISSUE TITLE
Alert PTR record lookup fixture/method proposal

### ISSUE THREAD

**Issue by claudijd** [mozilla/MozDef#762]
When I have an alert in MozDef that fires, it would be infinitely more helpful if for private IP addresses (any RFC1918) that we had a method/fixture available to alert writers to be able to translate any IP address in a summary into a the following:

"192.168.1.1" => "192.168.1.1 (foo.example.com)"

If a PTR record is not available, just return the original string.

The rationale behind only resolving PTRs from RFC1918 is because you don't want to leak the PTR resolution to an attacker who's outside your organization.

I was thinking this could start as a feature that alert writers can elect to use as a "mix-in", but could also translate just as easily into a generic feature set where any and all RFC1918 in any summary can be resolved to assist IR personnel in making quick decisive action.

**Comment by mpurzynski** [comment]
This requires alert plugins to be read-write, something I'm working on right now (literally). This alert plugin would query infoblox and maybe some other databases.
