### ISSUE TITLE
Cloudy MozDef Cloudformation Does not Create Managed ES Service Linked Role

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#787]
Cloudformation can't form the es service linked role.  
```
aws iam create-service-linked-role --region {{ aws_region }} --aws-service-name es.amazonaws.com --description ansibled-es-role

```

**Comment by gene1wood** [comment]
Should now be [possible](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-servicelinkedrole.html)
