### ISSUE TITLE
Templatize mozdef alerts config.py file or refactor with everett to introduce the standard config parameter pipeline

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#844]
Configuration is abstract in these two locations and does not conform to the standard env var pattern introduced in the infosec_workweek branch.  Please make it conform and if at all possible drop the dependence on the from alerts lib.config pattern.  

https://github.com/mozilla/MozDef/blob/master/alerts/celeryconfig.py#L3
https://github.com/mozilla/MozDef/blob/master/alerts/lib/config.py

**Comment by Phrozyn** [comment]
This is no longer an issue as celeryconfig.py is no longer a part of the code base.

**Comment by pwnbus** [comment]
After some discussion, I think we're gonna reopen this issue, but add some more context to it.

IMO the core issue here is that we're using hardcoded files to define what alerts are running, when it would be nice to support this configuration via environment variables (so in environments like docker, this is a bit easier to configure).
