### ISSUE TITLE
Move lost mozdef mq cfn to a branch

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#845]
Amazon MQ only support amqp protocol 1.0 where rabbit supports amqp 0.9.1.  The work to integrate amazon MQ has been removed from the project but remains in history.  Either:

* Retrieve this from commit history and preserve in a branch 
OR 
* Add an additional make target and parent-stack that includes this in order to facilitate future development on moving to amazon MQ

**Comment by gene1wood** [comment]
The substack template was actually left in place, though unused at

https://github.com/mozilla/MozDef/blob/master/cloudy_mozdef/cloudformation/mozdef-mq.yml

#831 is where reference to this template was removed from the parent
