### ISSUE TITLE
Configure mozdef to use Cloudtrail and SQS

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#847]
Note: This may involve refactoring these workers.  

In a subsequent sprint @gene1wood did the work necessary to give the mozdef instance the ability to query cloudtrail using the API and added queues with managed SQS policies.  This task involves refactoring OR finding a way to configure these workers to use the AWS IAM AssumeRole provided in instance to ingest data.

( Optionally these could likely be re-written as lambda functions )

**Comment by gene1wood** [comment]
This is resolved with #880 #879 #876 #868 #867 #866 and #840
