### ISSUE TITLE
Fix hard coded boto regions keys and secrets

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#849]
There are a number of places where the default boto credential handler / config system has been overridden.  

We need to preserve the current behavior by introducing configuration and allow boto or boto3 to follow the default chain.

This is related to #847

**Comment by gene1wood** [comment]
This is resolved in the cloudtrail es worker but not the sqs or snstosqs workers. As we don't require those two workers for cloudtrail (though we will need sqs for GuardDuty), I think further work on this doesn't block getting MozDef working in AWS (with only CloudTrail ingestion).

I'm going to remove the cloud label on this as I'm going to work on this in a general sense across all workers.

**Comment by gene1wood** [comment]
Agreed. I would work with @andrewkrug to ensure that the MozDef customers who needed this can confirm that it's working for them. Hate to close this, have it fall of the radar and then find out long down the road that the customer is still waiting on it
