### ISSUE TITLE
Add a contributing.md

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#863]
Add a contributing.md to the MozDef repository inspired by some combination of the following:

* https://mozillascience.github.io/working-open-workshop/contributing/
* https://github.com/mozilla-iam/mozilla-iam/blob/master/CONTRIBUTING.md
* https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md

Ideally we would complete a first iteration of this and publicly publish prior to November 25, 2018.

**Comment by gene1wood** [comment]
@andrewkrug As there [is a contributing file in mozdef](https://github.com/mozilla/MozDef/blob/master/CONTRIBUTING.md) are you thinking of changes to it, or an additional one specific to the cloud portion? (or something else)
