### ISSUE TITLE
Add a one click launch button to the README

### ISSUE THREAD

**Issue by andrewkrug** [mozilla/MozDef#865]
Add a one click launch button to the README, docs, or cloud quickstart.  

This will require the AMI to be public.

Instructions here:
https://aws.amazon.com/blogs/devops/construct-your-own-launch-stack-url/
For alpha it's likely fine for this to be in us-west-2 ONLY.

**Comment by gene1wood** [comment]
Fixed in 1780aef700f0a16b72546d9bdba0be2309dd7dec
