### ISSUE TITLE
Improve GitHub repo issue template, make it easier to fill out, briefer and more accessible

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#883]
I think the current issue template could use some improvement. Here's the current one

```
<!---
Verify first that your issue/request is not already reported on GitHub.
Also test if the latest release, and master branch are affected too.
-->

#### ISSUE TYPE
<!--- Pick one below and delete the rest: -->
 - Bug Report
 - Feature Idea
 - Documentation Report

#### COMPONENT NAME
<!--- Name of the cron/worker/module/plugin/task/feature -->

#### CONFIGURATION
<!---
Mention any settings you have changed/added/removed 
-->

#### OS / ENVIRONMENT
<!---
Mention the OS you are running MozDef from and versions of all MozDef components you are running
-->

#### DESCRIPTION
<!--- Explain the problem briefly -->

#### STEPS TO REPRODUCE
<!---
For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used.
-->

<!--- Paste any log messages/configurations/scripts below that are applicable -->


<!--- You can also paste gist.github.com links for larger files -->

#### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->

#### ACTUAL RESULTS
<!--- What actually happened?  -->
```

and here's a proposed change. With this proposed change I have some questions
* What is a "Documentation Report"?
* How does one determine the version of the MozDef components they're using?

```
<!-- Please use either the Bug or Feature request sections, fill the appropriate one out and delete the other -->
# Issue type : Bug
- [ ] I've checked existing issues to see if this problem has already been reported
- Component name : cron / worker / module / plugin / task / feature <!-- choose one -->
- Operating system :
- MozDef components versions : 

<!-- Please share 
* any custom configuration
* steps to reproduce the problem
* expected results
* actual results
* any log messages
-->

# Issue type : Feature request
```

**Comment by andrewkrug** [comment]
Do we really need operating system?  Can't we just make a support statement of "mozdef is only supported on RHEL/CentOS 7.x"

**Comment by pwnbus** [comment]
I think it overall looks good, to answer a couple of your questions @gene1wood 
1. My guess is that was meant to describe a problem in any of our documentation
2. I'm not sure there's a way, besides unless git log to get the commit hash or something like that

**Comment by pwnbus** [comment]
@Phrozyn mind taking a look here since you were the original creation of that template I believe?

**Comment by gene1wood** [comment]
So, if we take out "Operating system" and MozDef component version, little is left in this template.

* Asking people if this is a bug or feature request
* Trying to cue them to search for an existing issue first
* Giving them a list of MozDef components, though I don't think we do anything with this
* Asking them to give steps to reproduce, expected results and actual results
* Asking for custom configuration and log messages

Can I propose that we actually just remove the template entirely? It seems like we're [pre-optimizing](http://wiki.c2.com/?PrematureOptimization) to handle problems with the level of detail provided in issues (unless there's been a historical problem with people submitting vague issues that require a lot of back and forth to gather details about).

@Phrozyn  ?

**Comment by gene1wood** [comment]
Phrozyn suggested calling out the challenges I'm facing with the template

* The two and a half pages of content in the blank issue when opening it makes me reluctant to file an issue because of the time commitment needed to read through and fill out those pages. In response I've found myself deleting the template, unread and filing a 4 or 5 line issue.
* Being asked to `test if the latest release, and master branch are affected too.` is confusing for feature requests and as a user, a barrier to entry in reporting a bug, not having an environment to stand up and test these in. Considering I'm in infosec, and I don't have a way to easily test this, a user outside the team, to which this template is targeted would find this a disincentive to report a bug.
* I don't know what a ` - Documentation Report` is. Pwnbus suggested it was likely a bug report for documentation.
* When asked to `Mention any settings you have changed/added/removed` I'm unsure what settings would be germane or where to find them. This likely stems from my lack of understanding of the configuration system for MozDef in general. Again, if it's hard for me and I'm in the team, the user this is targeted for may have trouble with this step.
* I didn't understand how to determine the version of MozDef components as asked for in `Mention the OS you are running MozDef from and versions of all MozDef components you are running` and it sounds like there is no way to determine that.
* The 4th level deep heading style seems odd
* Mentioning that `You can also paste gist.github.com links for larger files` feels unnecessary. This seems like another instance of pre-optimizing for problems we don't have (of users either pasting large blocks of text into issues or not providing the data because they don't know where to put it)
* `show exactly how to reproduce the problem` makes me feel like I'm at risk of not providing the level of specificity that this template demands. As a user that this is targeted at, we should be more welcoming.
