### ISSUE TITLE
Make meteor drop down menu for kibana dashboards do something when there are no dashboards

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#899]
Currently when the kibana dashboard list dropdown menu has no dashboards, it doesn't do anything.

Let's change this so that if there are no dashboards, the kibana drop down instead just takes the user to kibana.

**Comment by jeffbryner** [comment]
The root menu anchor (the thing saying 'kibana' should take you to kibana. does it not?

**Comment by gene1wood** [comment]
Oh, interesting. On our cloudy mozdef deployment it links to`http://localhost:9090/app/kibana#` instead of the actual kibana URL. Looks like we may have missed that localization piece.

I'll close this issue and open on specific to the cloud deployment not using the environment variable. Not sure why I dind't notice that the drop down already had a link (just not the right one)
