### ISSUE TITLE
Create kibana dashboard for CloudTrail in defaut cloud deployment

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#900]
Currently the dropdown menu for Kibana has no dashboards by default. Let's provision one by default.

**Comment by gene1wood** [comment]
@pwnbus When you say that this requires creating those two files, do you mean those two files were created in #1043 or the creation of those files is work still required to have a default CloudTrail dashboard?

**Comment by pwnbus** [comment]
I'm just stating what work has been done as a result in case folks wanted to add/update/improve a dashboard.

Sorry for the confusion, I suppose the PR is somewhat self descriptive :)
