### ISSUE TITLE
Cloud MozDef Meteor kibana drop down links to wrong link

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#904]
The kibana dropdown menu in the meteor interface links to `http://localhost:9090/app/kibana#` instead of the actual kibana URL that's conveyed in environment variables.

**Comment by gene1wood** [comment]
So #926 doesn't fix this because it sets the meteor link to kibana, not to the OIDC reverse proxy container URL which fronts the AWS ES Kibana URL, but instead the raw AWS ES Kibana URL.

The result is that the URL isn't reachable because you're supposed to contact it via the reverse proxy.

So ways we could approach fixing this
* Do some [javascript trickery](https://stackoverflow.com/a/13522508/168874) to allow us to have a relative URL with a port number and set the kibana URL to a relative URL with port
* Change the 2 mozilla.oidc.reverseproxy docker containers into a single one and add support for mozilla.oidc.accessproxy to accept not a single `path`/`backend` pair but an arbitrary number of pairs such that each path would be proxied back to a different backend. Then with these 2 containers consolidated into one, the kibana URL becomes a simple relative URL with no special port number
* Have the FQDN that the site is accessed at, passed in to the instance (see #871 ) so we can construct the kibana URL by combining that value plus a port plus a kibana path

**Comment by jeffbryner** [comment]
The end result should be like: https://cloudymozdef.security.allizom.org:9090/_plugin/kibana
Ideally we pass this as OPTIONS_METEOR_KIBANAURL so meteor doesn't have to guess and it's just set as an environment variable. 
Any way to derive this from the bits already in cloudformation?

**Comment by jeffbryner** [comment]
Ahh, we could do a thing where if the URL isn't set (i.e. the ENV is empty), or if it's set to some special value OPTIONS_METEOR_KIBANAURL=figureitout then we construct it via https://docs.meteor.com/api/core.html#Meteor-absoluteUrl or some other javascript magic

**Comment by jeffbryner** [comment]
I propose we adopt the latter.. a special kibanaurl variable/keyword that tells meteor to set the url relative to whatever dns the instance lands on: 

i.e. OPTIONS_METEOR_KIBANAURL=http://relative:9090/app/kibana

would parse via new URL(OPTIONS_METEOR_KIBANAURL) as hostname==relative, and Meteor can do a call to Meteor.absoluteUrl() to get the real hostname and substitute it.
