### ISSUE TITLE
Meteor causing 'make build-tests' to hard fail

### ISSUE THREAD

**Issue by claudijd** [mozilla/MozDef#907]
I tried running make build-tests today and it fails on Mac OSX.

 (master) $ docker --version
Docker version 18.06.0-ce, build 0ffa825
 (master) $ docker-compose --version
docker-compose version 1.22.0, build f46880f

```...
tar: .meteor/packages/babel-compiler/.7.2.0.1offs5e.f8sn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/.bin: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.2.0.1offs5e.f8sn++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.2.0.1offs5e.f8sn++os+web.browser+web.browser.legacy+web.cordova/npm: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler/.7.2.0.1offs5e.f8sn++os+web.browser+web.browser.legacy+web.cordova: Directory renamed before its status could be extracted
tar: .meteor/packages/babel-compiler: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
ERROR: Service 'meteor' failed to build: The command '/bin/sh -c tar -xzf /opt/mozdef/meteor.tar.gz -C /opt/mozdef/meteor' returned a non-zero code: 2
make: *** [build-tests] Error 1```

**Comment by claudijd** [comment]
I switched to storage-driver aufs and noted it in the [guide wip](https://github.com/mozilla/MozDef/pull/908), though expect possible breakage if Docker doesn't fix the issue we're working around before deprecation.

<img width="596" alt="screen shot 2018-10-30 at 1 32 41 pm" src="https://user-images.githubusercontent.com/794283/47745079-312c7f80-dc59-11e8-972b-701796525fda.png">

**Comment by mpurzynski** [comment]
Per docker best practices I ran it 10 times in a loop and it worked.
