### ISSUE TITLE
Revamps make build env fails, possible /var/cache/yum bloat issue

### ISSUE THREAD

**Issue by claudijd** [mozilla/MozDef#911]
One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Insufficient space in download directory /var/cache/yum/x86_64/7/base
    * free   0 
    * needed 100 k
ERROR: Service 'elasticsearch' failed to build: The command '/bin/sh -c useradd -ms /bin/bash -d /opt/mozdef -m mozdef &&   yum install -y java-$ES_JAVA_VERSION &&   mkdir -p /opt/mozdef/envs &&   curl -s -L https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-$ES_VERSION.tar.gz  | tar -C /opt/mozdef -xz &&   mv /opt/mozdef/elasticsearch-$ES_VERSION /opt/mozdef/envs/elasticsearch &&   chown -R mozdef:mozdef /opt/mozdef &&   mkdir /var/log/elasticsearch &&   chown -R mozdef:mozdef /var/log/elasticsearch &&   mkdir /var/lib/elasticsearch &&   chown -R mozdef:mozdef /var/lib/elasticsearch &&   yum clean all' returned a non-zero code: 1
make: *** [build-tests] Error 1
 (master) $ git log -1
commit 94628b17b68942f400e5e3ebe8dc908b82bd6629 (HEAD -> master, origin/master, origin/HEAD)
Merge: 6598a030 bbb9ab7a
Author: Brandon Myers <pwnbus@users.noreply.github.com>
Date:   Tue Oct 30 18:50:04 2018 -0500

    Merge pull request #909 from gdestuynder/master
    
    Revamp docker build system

**Comment by claudijd** [comment]
$ docker --version
Docker version 18.06.0-ce, build 0ffa825
$ docker-compose --version
docker-compose version 1.22.0, build f46880f

**Comment by claudijd** [comment]
I was able to get this to build, though, I suspect this is not an isolated issue and could come back to bite some users, so I'm leaving it open until perhaps we address the /var/cache/yum bloat feedback.

**Comment by caggle** [comment]
I encountered the same issue while trying to build, after I got past the 'tar' bug on overlayfs (by making docker use the aufs, as was suggested on the web and in Slack).

@claudijd how did you get it to still build?

**Comment by claudijd** [comment]
`docker image prune && docker image prune -a` made some room.  I suspect this was made worse by running `make build-test` which previously built all containers and may have bloated the base image enough to be an issue.

**Comment by caggle** [comment]
I am unable to get past this issue, even after running a multitude of `docker rm` and `docker prune` commands. Strange...I am stuck.
I am following the alert development guide also. Getting this error on the `make build-tests` step.

**Comment by caggle** [comment]
OK, I was able to figure this out. For reference in case others run into this problem, I simply increase the disk image size for Docker disk image:
![image](https://user-images.githubusercontent.com/30646014/47835650-2b6da000-ddf9-11e8-8758-eeb19c7c631f.png)

**Comment by pwnbus** [comment]
I created https://github.com/mozilla/MozDef/pull/1095 which removes about 100mb of space per container.
