### ISSUE TITLE
WSS errors when using Metero UI

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#924]
Currently using the meteor UI shows errors like this in the console

`Firefox can’t establish a connection to the server at wss://cloudymozdef.security.allizom.org/sockjs/777/e2wsk_9k/websocket.`

Andrew suggests this is because we don't forward websockets through the openresty reverse proxy. And that we don't use the websockets features of meteor so it doesn't matter.

Can we set it up to forward these to get rid of these errors?

**Comment by jeffbryner** [comment]
We disable websockets here: 
https://github.com/mozilla/MozDef/blob/master/meteor/server/mozdef.js#L16

It may be that you are seeing just one or two before that setting takes effect?

**Comment by gene1wood** [comment]
Yes, previously when we had the OIDC login issue, the errors were continuous and repeated, but now it does only happen like once. Cool.
