### ISSUE TITLE
Pass good ROOTURL to meteor

### ISSUE THREAD

**Issue by gene1wood** [mozilla/MozDef#925]
The ROOTURL variable in meteor isn't being set correctly. It should be set through env variables to something like this.

` OPTIONS_METEOR_ROOTURL = https://cloudymozdef.security.allizom.org/`

We'll need to somehow know what domain name is being used to access the site which means this may depend on #871

**Comment by andrewkrug** [comment]
Complete in https://github.com/mozilla/MozDef/commit/995d730c9c934aa0549e9d19d54ee32e5035b5c1
