### ISSUE TITLE
Example log input - Docs

### ISSUE THREAD

**Issue by darakian** [mozilla/MozDef#952]
Hey all,

I'm trying to work out how to get rsyslog to properly input logs to MozDef and in testing input with nc I'm running into issues. Currently I'm using commands of the form
```
echo "PUT / $var" | nc localhost 8080
```
and I'm just getting Bad Request responses from nginx. Do simple put examples exist in the docs? If so can someone point me at them? If not can I request that some be added?

For testing I'm using the example json on this page for the data in $var
https://mozdef.readthedocs.io/en/latest/usage.html

**Comment by jeffbryner** [comment]
@Phrozyn can you help with this? Might be a good opportunity to share the updated syslog configs.

**Comment by darakian** [comment]
Of course. From what I'm reading Rsyslog has just introduced a module called omhttp for outputting http formatted logs. A json template is needed and I intended to create one for my own needs which I can share.

At the moment I'm still uncertain of how to format input into MozDef.

**Comment by jeffbryner** [comment]
The sample/demo events may be a helpful reference: 
https://github.com/mozilla/MozDef/blob/master/examples/demo/sampleevents/events-benign.json

You can use curl to post those to the loginput endpoint ( http://localhost:8080/events/) as is done in the sampledata docker container if you just want to test connectivity. 
https://github.com/mozilla/MozDef/blob/master/examples/demo/sampleData2MozDef.py is the program in the sampledata container that does the lifting of those particular json files into mozdef, but it gets fancy to use current dates, randomize ip addresses etc. A simple post of json should suffice.

**Comment by Phrozyn** [comment]
hi @darakian,

I wanted to let you know you can also use syslog-ng to format events into json format and post to the rabbitmq  eventtask queue, or send to loginput - either way.
If you would like more information on either of these options I would be happy to provide some information.

**Comment by pwnbus** [comment]
If you're using the docker environment, you can also send syslog events to <docker host ip>:514.

**Comment by jeffbryner** [comment]
@darakian I finally got what you are trying to do and I think the issue is that netcat doesn't know HTTP post. 

If you want to just post some json to mozdef do something like: 
```
curl -v --header "Content-Type: application/json"   --request POST   --data '{"tags": ["test"],"summary": "just a test"}'   http://localhost:8080/events
```
where http://localhost:8080 is whatever is running the 'loginput' service. 
The 'data' curl option is what gets posted as json to MozDef.

**Comment by darakian** [comment]
@jeffbryner. The lack of http support would do it I guess. Thanks!

**Comment by jeffbryner** [comment]
Cool, I'll add a bit to the docs.
