### ISSUE TITLE
GPL 2.0 license in source tree

### ISSUE THREAD

**Issue by hyandell** [mozilla/MozDef#969]
The mozdef_util directorie's README and setup.py both state the license is MPL 2.0, however, the https://github.com/mozilla/MozDef/blob/master/mozdef_util/LICENSE file contains GPL 2.0 rather than MPL 2.0. 

Is the GPL 2.0 file an error?

**Comment by andrewkrug** [comment]
@hyandell it's most definitely an error.  Likely generated by Cookie Cutter.  If you'd like to PR a change to MozDef with an MPL 2.0 license we would very much appreciate setting things correct.

**Comment by jeffbryner** [comment]
lets just rm -rf the errant license? since all of mozdef is already covered by https://github.com/mozilla/MozDef/blob/master/LICENSE

**Comment by jeffbryner** [comment]
On 2nd thought since people probably arrive there via the package, I pushed a branch/pr to fix

**Comment by hyandell** [comment]
Thanks all :)
