### ISSUE TITLE
Allow alert configuration via environment variables

### ISSUE THREAD

**Issue by pwnbus** [mozilla/MozDef#982]
This would allow us to use an environment variable to control which alerts to turn on, and the frequency of them.

We'll modify https://github.com/mozilla/MozDef/blob/master/alerts/lib/config.py#L12 to look for the environment variable, then parse out the datastructure etc.

**Comment by darakian** [comment]
By 'environment variable' do you actually mean shell variables or could this also mean something like a config file?

**Comment by jeffbryner** [comment]
I wonder if we need a schedule stanza at all? What if we auto scheduled any .py file that lives in the /alerts directory to run? Mostly they all run every minute currently (since they take<1sec 99% of the time).

This would make it easy to deploy an alert.. simply copy the file into a directory. 

Thoughts?

**Comment by Phrozyn** [comment]
That would make it easy but difficult to turn off a particular alert
without having to manually remove it from the directory. That's not really
ideal.

**Comment by darakian** [comment]
@jeffbryner That certainly could work for my purposes. It would be nice to set some queries to run at a lower rate if they become complex or if only a certain amount of activity is expected over a given time frame ex. 10 logins an hour is normal, 11 an hour implies certain doom.

Another option would be to have the schedules be configurable via a web page and/or http endpoints. Default everything on/off and running on the minute. Let users configure from there. Maybe keep the two example alerts as the only ones turned on so as not to overwhelm new users.

**Comment by jeffbryner** [comment]
Good point @Phrozyn about turning off an alert. @darakian true, a UI for checking/unchecking alerts would be more functional. Usually thresholds are set *in* the alert so the frequency of the alert running doesn't matter. Alerts also mark events as 'alerted' when they match so there isn't a concern about overlapping time, etc.

**Comment by darakian** [comment]
Ah yes, I forgot about the thresholds in the py files. Perhaps those should be user configurable/override-able via a gui/end points?
